[changelog]
header = """
# Changelog

Todos los cambios relevantes serán documentados aquí.
"""

body = """
{% if version %}
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## Unreleased
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""

footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = "v[0-9].*"

[commit_types]
feat = { group = "Features" }
fix = { group = "Bug Fixes" }
refactor = { group = "Refactoring" }
docs = { group = "Documentation" }
test = { group = "Tests" }
chore = { group = "Chore" }
